### ISSUE TITLE
Wrong enum value

### ISSUE THREAD

**Issue by buldo** [Nihlus/PulseSharp#1]
https://github.com/Nihlus/PulseSharp/blob/12cd363a5a895b9bb4007f725b860ac98f1bb2fb/PulseSharp/Enums/SampleFormat.cs#L48

Should be `Invalid = -1`

**Comment by Nihlus** [comment]
Fixed. I'm surprised someone is actually using this!

**Comment by buldo** [comment]
Actually I wrote own wrapper and after that found out that Your wrote same code before me :)
